townsNews/townsNews/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from newportal import views
from newportal.forms import CustomLoginForm

admin.site.index_template = "admin/index.html"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('errors/', views.error_list_view, name='error_list'),
    path('activity/authors/', views.author_activity, name='author_activity'),
    path('activity/blocks/', views.most_viewed_blocks, name='most_viewed_blocks'),
    path('tracker/popular-views/', views.popular_articles_views, name='popular_articles_views'),
    path('tracker/popular-saves/', views.popular_articles_saves, name='popular_articles_saves'),
    path('word/prohibited-words/', views.prohibited_words_report, name='prohibited_words_report'),
    path('word/seo-titles/', views.seo_titles_report, name='seo_titles_report'),
    path('word/tags/', views.tags_report, name='tags_report'),
    path('count/updates', views.news_updates, name='news-updates'),
    path('count/time', views.news_time, name='news-time'),
    path('', views.index, name='index'),  # Головна сторінка
    path('articles/', views.article_list, name='article-list'),  # Список статей
    path('articles/<int:pk>/', views.article_detail, name='article-detail'),  # Деталі статті
    path('articles/<int:pk>/save/', views.save_for_later, name='save-for-later'),  # Збереження статті
    path('articles/<int:pk>/comment/', views.add_comment, name='add-comment'),  # Додавання коментаря
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                authentication_form=CustomLoginForm
                                                ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('saved/', views.saved_articles, name='saved-articles'),
    path('saved/<int:pk>/remove/', views.remove_from_saved, name='remove-from-saved'),
    path('settings/', views.edit_user_site_settings, name='edit-user-site-settings'),
    path('statistics/', views.article_statistics, name='article-statistics'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete-comment'),
    path('articles/create/', views.create_article, name='create-article'),
    path('articles/<int:pk>/edit/', views.edit_article, name='edit-article'),
    path('articles/<int:pk>/delete/', views.delete_article, name='delete-article'),
    path('add/', views.create_article, name='article-add'),
    path('profile/', views.edit_profile, name='edit-profile'),
    path('users/', views.manage_users, name='user-management'),
    path('users/add/', views.add_user, name='add-user'),
    path('users/<int:user_id>/ban/', views.ban_user, name='ban-user'),
    path('users/<int:user_id>/delete/', views.delete_user, name='delete-user'),
    path('api/articles/', views.articles_api, name='articles_api'),
    path('how-listen/', views.how_listn, name='how-listen'),
    path('comment-rules/', views.comment_rules, name='comment-rules'),
    path('about-us/', views.about_us, name='about-us'),
    path('our-codex/', views.our_codex, name='our-codex'),
    path('legal-aspects/', views.legal_aspects, name='legal-aspects'),
    path('feedback/', views.feedback, name='feedback'),
    path('api/weather/', views.get_weather, name='get-weather'),
    path('api/currency_rates/', views.get_currency_rates, name='get-currency-rates'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

townsNews/newportal/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.models import User
from django.db.models.signals import post_migrate


class Author(models.Model):
    name = models.CharField(max_length=50,
                            help_text="Введіть ім'я автора",
                            verbose_name="Ім'я автора")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "автори"
        verbose_name_plural = "Автори"


class Tag(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введіть тег",
                            verbose_name="Теги")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "тег"
        verbose_name_plural = "Теги"


class Article(models.Model):
    title = models.CharField(max_length=100,
                             verbose_name='Назва статті')
    article_text = models.TextField(max_length=1000,
                                    verbose_name='Текст статті',
                                    default="Поле статті")
    author = models.ForeignKey(Author, on_delete=models.CASCADE,
                               verbose_name="Автор")
    date_of_publication = models.DateField(verbose_name='Дата публікації',
                                           null=True,
                                           blank=True)
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    views_count = models.IntegerField(default=0, verbose_name="Кількість переглядів")
    image = models.ImageField(upload_to='article_images/', null=True, blank=True, verbose_name="Зображення")

    def display_tag(self):
        return ', '.join([tag.name for tag in self.tags.all()])

    display_tag.short_description = 'Теги'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article-detail',
                       args=[str(self.id)])

    class Meta:
        verbose_name = "статтю"
        verbose_name_plural = "Статті"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Введіть текст коментаря')
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата створення')

    def __str__(self):
        return f'Коментар від {self.user.username} до {self.article.title}'

    class Meta:
        verbose_name = "коментар"
        verbose_name_plural = "Коментарі"


class SavedArticle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='saved_articles')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    saved_at = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата збереження')

    def __str__(self):
        return f'{self.user.username} зберіг "{self.article.title}"'

    class Meta:
        verbose_name = "збережену статтю"
        verbose_name_plural = "Збережені статті"


class UserSiteSettings(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="site_settings"
    )
    font_color = models.CharField(max_length=7, default='#ffffff')
    background_color = models.CharField(max_length=7, default='#002f31')
    font_size = models.IntegerField(default=14, validators=[MinValueValidator(12), MaxValueValidator(36)])

    def __str__(self):
        return f"Site settings for {self.user.username}"


class UserBan(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    ban_end = models.DateTimeField()

    def is_banned(self):
        return self.ban_end > timezone.now()

    def remaining_time(self):
        return self.ban_end - timezone.now()

    def __str__(self):
        return f'{self.user.username} - заблокований до {self.ban_end}'

    class Meta:
        verbose_name = "Блокування користувача"
        verbose_name_plural = "Блокування користувачів"


class SelectedFacade(models.Model):
    FACADE_CHOICES = {
        ("error", "error"),
        ("activity", "activity"),
        ("tracker", "tracker"),
        ("word", "word"),
        ("count", "count")
    }

    selected_facade = models.CharField(max_length=20,
                                       default='error',
                                       choices=FACADE_CHOICES,
                                       verbose_name='Виберіть варіант дослідження')

    def save(self, *args, **kwargs):
        if SelectedFacade.objects.exists() and not self.pk:
            raise ValidationError("Може бути лише один варіант дослідження")
        super(SelectedFacade, self).save(*args, **kwargs)

    def __str__(self):
        return ''

    class Meta:
        verbose_name = "звіт"
        verbose_name_plural = "Звіти"


class ProhibitedWord(models.Model):
    word = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.word

townsNews/newportal/forms.py
from datetime import timedelta
import re
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from .models import Comment, Article, UserBan, UserSiteSettings


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'no-copy-paste'}),
        label="Пароль"
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'no-copy-paste'}),
        label="Підтвердження пароля"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_password(self):
        password = self.cleaned_data.get("password")
        validate_strong_password(password)
        return password

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password != password_confirm:
            raise forms.ValidationError("Паролі не збігаються")
        return password_confirm


def validate_strong_password(password):
    if len(password) < 8:
        raise ValidationError('Пароль має містити щонайменше 8 символів.')
    if not re.search(r'[A-Z]', password):
        raise ValidationError('Пароль має містити хоча б одну велику літеру.')
    if not re.search(r'[!@#$%^&*]', password):
        raise ValidationError('Пароль має містити хоча б один спецсимвол: !@#$%^&*')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Введіть ваш коментар...'}),
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({
            'class': 'form-control comment-input',
            'placeholder': 'Напишіть свій коментар тут...'
        })


class UserSiteSettingsForm(forms.ModelForm):
    class Meta:
        model = UserSiteSettings
        fields = ['font_color', 'background_color', 'font_size']
        widgets = {
            'font_color': forms.TextInput(attrs={'type': 'color'}),
            'background_color': forms.TextInput(attrs={'type': 'color'}),
            'font_size': forms.NumberInput(attrs={
                'type': 'range', 'min': 12, 'max': 36, 'step': 1, 'class': 'slider'
            })
        }


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'article_text', 'author', 'tags', 'date_of_publication', 'image']
        widgets = {
            'date_of_publication': forms.DateInput(attrs={'type': 'date'}),  # Вибір дати
        }


BAN_PERIOD_CHOICES = [
    (1, '1 день'),
    (7, '1 тиждень'),
    (30, '1 місяць'),
    (365, '1 рік'),
    (99999, 'Довічно'),
]


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = "Ім'я"
        self.fields['email'].label = "Email"
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget = forms.EmailInput(attrs={'class': 'form-control'})


class BanUserForm(forms.Form):
    period = forms.ChoiceField(choices=BAN_PERIOD_CHOICES, label="Термін блокування")

    def apply_ban(self, user):
        period_days = int(self.cleaned_data['period'])
        if period_days == 99999:
            ban_end = timezone.now() + timedelta(days=365*100)
        else:
            ban_end = timezone.now() + timedelta(days=period_days)
        UserBan.objects.update_or_create(user=user, defaults={'ban_end': ban_end})


class CustomLoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        try:
            user_ban = UserBan.objects.get(user=user)
            if user_ban.is_banned():
                remaining_time = user_ban.remaining_time()
                # Виведення повідомлення про бан без локалізації
                raise forms.ValidationError(
                    f'Ваш акаунт заблокований. Залишилось: {remaining_time.days} днів, {remaining_time.seconds // 3600} годин.',
                    code='banned',
                )
        except UserBan.DoesNotExist:
            pass  # Якщо бану немає, дозволяємо вхід


class AddUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Пароль")
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Підтвердження пароля")

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password != password_confirm:
            raise forms.ValidationError("Паролі не збігаються")
        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

townsNews/newportal/templates/catalog/add_users.html
{% extends 'base_generic.html' %}
{% load static %}

{% block content %}
<div class="container-login">
    <h2>Додати нового користувача</h2>

    {% if form.errors %}
    <ul class="form-errors alert alert-danger" style="list-style: none;">
        {% for field in form %}
            {% for error in field.errors %}
            <li><strong>{{ field.label }}</strong>: {{ error }}</li>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form method="post" id="registration-form" novalidate>
        {% csrf_token %}
        <div class="form-reg">
            {{ form.username.label_tag }}
            {{ form.username }}
        </div>
        <div class="form-reg">
            {{ form.email.label_tag }}
            {{ form.email }}
        </div>
        <div class="form-reg">
            {{ form.password.label_tag }}
            {{ form.password }}
            <ul id="password-checklist"
                class="text-muted"
                style="font-size:0.95em; margin-bottom:0; margin-top:4px; padding-left:18px;">
                <li id="len-check">Мінімум 8 символів</li>
                <li id="upper-check">Хоча б одна велика літера</li>
                <li id="spec-check">Хоча б один спецсимвол (!@#$%^&*)</li>
            </ul>
        </div>
        <div class="form-reg">
            {{ form.password_confirm.label_tag }}
            {{ form.password_confirm }}
            <span id="match-check"
                  class="text-muted"
                  style="font-size:0.95em; display:block;"></span>
        </div>
        <button class="sub-btn btn btn-primary" id="submit-btn">Створити користувача</button>
    </form>

    <p style="margin-top:1em;">
        <a href="{% url 'user-management' %}">&larr; Повернутись до списку користувачів</a>
    </p>
</div>

<script>
// Блокуємо copy/paste у полях password
(function() {
    const passFields = document.querySelectorAll('input[type="password"]');
    passFields.forEach(field => {
        field.setAttribute('autocomplete', 'new-password');
        ['copy','paste','cut','contextmenu'].forEach(ev =>
            field.addEventListener(ev, e => e.preventDefault())
        );
    });
})();

// Live-валидація паролю
(function() {
    const pwd = document.getElementById("id_password");
    const conf = document.getElementById("id_password_confirm");
    const btn = document.getElementById("submit-btn");
    const len = document.getElementById("len-check");
    const up  = document.getElementById("upper-check");
    const spc = document.getElementById("spec-check");
    const mch = document.getElementById("match-check");

    function validatePassword() {
        const v = pwd.value;
        let ok = true;
        // довжина
        if (v.length >= 8) { len.style.color = "green"; }
        else { len.style.color = "red"; ok = false; }
        // велика літера
        if (/[A-ZА-ЯЁЇЄІ]/.test(v)) { up.style.color = "green"; }
        else { up.style.color = "red"; ok = false; }
        // спецсимвол
        if (/[!@#$%^&*]/.test(v)) { spc.style.color = "green"; }
        else { spc.style.color = "red"; ok = false; }

        // збіг
        if (!conf.value) {
            mch.textContent = ""; ok = false;
        } else if (v === conf.value) {
            mch.textContent = "Паролі співпадають"; mch.style.color = "green";
        } else {
            mch.textContent = "Паролі не співпадають"; mch.style.color = "red";
            ok = false;
        }

        btn.disabled = !ok;
    }

    [pwd, conf].forEach(fld => fld.addEventListener("input", validatePassword));
    document.addEventListener("DOMContentLoaded", ()=> btn.disabled = true);
})();
</script>
{% endblock %}

townsNews/newportal/templates/catalog/article_detail.html
{% extends 'base_generic.html' %}

{% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block title %}{{ article.title }}{% endblock %}

{% block content %}
        {% if is_admin %}
            <div class="btn-block">
                <strong>Керування новиною</strong><br>
                <a href="{% url 'edit-article' article.pk %}" class="btn btn-warning btn-sm edit-btn">Редагувати</a>
                <form action="{% url 'delete-article' article.pk %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">Видалити</button>
                </form>
            </div>
        {% endif %}
<div class="container-detail mt-5">
    <div class="row">
        <!-- Контент статті -->
        <div class="col-sm-8">
            <h1 class="article-title mb-4" style="color: #ffcc00">{{ article.title }}</h1>
            {% if article.image %}
                <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width: 70%; margin-bottom: 20px;">
            {% endif %}
            <p class="text-muted"><strong>Автор:</strong> {{ article.author.name }}</p>
            <p class="text-muted"><strong>Опубліковано:</strong> {{ article.date_of_publication|date:"d M Y" }}</p>
            <div class="article-content mb-4">{{ article.article_text|linebreaksbr }}</div>

            <!-- Теги статті -->
            <p><strong>Теги:</strong>
                {% for tag in article.tags.all %}
                    <a href="{% url 'article-list' %}?tag={{ tag.id }}" class="badge badge-info">{{ tag.name }}</a>
                {% endfor %}
            </p>

            <!-- Зберегти статтю -->
            {% if user.is_authenticated %}
            <form action="{% url 'save-for-later' article.pk %}" method="post" class="mt-4">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-sm">Зберегти для подальшого читання</button>
            </form>
            {% endif %}

            <!-- Коментарі -->
            <hr>
            <h3 class="mb-3">Коментарі</h3>
            <ul class="list-unstyled">
                {% for comment in article.comments.all %}
                <li class="media mb-3">
                    <div class="media-body">
                        <h5 class="mt-0 mb-1">{{ comment.user.username }}</h5>
                        {{ comment.text }}

                        <!-- Показати кнопку видалення лише для адміністратора -->
                        {% if is_admin %}
                        <form action="{% url 'delete-comment' comment.id %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm">Видалити</button>
                        </form>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <p>Поки що немає коментарів.</p>
                {% endfor %}
            </ul>

            <!-- Додати коментар -->
            {% if user.is_authenticated %}
            <hr>
            <h4 class="mb-3">Додати коментар</h4>
            <form action="{% url 'article-detail' article.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ form.text.label_tag }}
                    {{ form.text }}
                </div>
                <button type="submit" class="btn btn-sm send-btn">Відправити</button>
            </form>
            {% else %}
            <p>Будь ласка, <a href="{% url 'login' %}?next={{ request.path }}">увійдіть</a>, щоб залишити коментар.</p>
            {% endif %}
        </div>

        <!-- Other news -->
        <div class="col-sm-4">
            <div class="another-news">
                <h3><a href="{% url 'article-list' %}">До інших новин</a></h3>
            </div>
        </div>

        <!-- Advertising -->
        <div class="advertising">
            <div class="advertising-content">
                <span class="ad-title">Тут може бути ваша реклама</span>
                <span class="ad-subtitle">Зв'яжіться з адміністрацією<br>для розміщення</span>
                <span class="ad-contact"><a href="https://mail.google.com/">infokyivlux@gmail.com</a></span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

townsNews/newportal/templates/catalog/article_form.html
{% extends 'base_generic.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

{% block title %}{{ is_editing|yesno:"Редагування статті,Нова стаття" }}{% endblock %}

{% block content %}
<div class="container-fluid mt-3 main-block">
    <div class="row justify-content-center first-block">
        <div class="col-lg-12">
            <div class="card shadow-sm border-0 block-form">
                <div class="card-header bg-primary text-white rounded-top">
                    <h2 class="text-center my-2">
                        {{ is_editing|yesno:"Редагувати статтю,Створити статтю" }}
                    </h2>
                </div>
                <div class="card-body p-4">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Титул статті -->
                        <div class="mb-3">
                            <label for="id_title" class="form-label">Заголовок статті</label>
                            <input type="text"
                                   class="form-control"
                                   id="id_title"
                                   name="title"
                                   placeholder="Введіть заголовок"
                                   value="{{ form.instance.title|default_if_none:'' }}" style="color: white">
                        </div>

                        <!-- Текст статті -->
                        <div class="mb-3">
                            <label for="id_article_text" class="form-label">Текст статті</label>
                            <textarea class="form-control"
                                      id="id_article_text"
                                      name="article_text"
                                      rows="6"
                                      style="color: white"
                                      placeholder="Введіть текст статті">{{ form.instance.article_text|default_if_none:'' }}</textarea>
                        </div>

                        <!-- Автор -->
                        <div class="mb-3">
                            <label for="id_author" class="form-label">Автор</label>
                            {% if form.fields.author.choices %}
                                <select class="form-control" id="id_author" name="author" style="color: white">
                                    {% for val, label in form.fields.author.choices %}
                                        <option value="{{ val }}"
                                            {% if form.instance.author and form.instance.author.pk == val %}selected{% endif %}
                                        style="color: black">{{ label }}</option>
                                    {% endfor %}
                                </select>
                            {% else %}
                                <input type="text" class="form-control" id="id_author" name="author"
                                       value="{{ form.instance.author|default_if_none:'' }}">
                            {% endif %}
                        </div>

                        <!-- Теги (ManyToMany, через ctrl+click) -->
                        <div class="mb-3">
                            <label for="id_tags" class="form-label">Теги</label>
                            <select class="form-control" id="id_tags" name="tags" style="color: white">
                                <option value="" {% if not form.instance.tags.all %}selected{% endif %} style="color: black">Оберіть тег</option>
                                {% for tag in form.fields.tags.queryset %}
                                    <option value="{{ tag.pk }}"
                                        {% if tag in form.instance.tags.all %}selected{% endif %}
                                    style="color: black">{{ tag.name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <!-- Дата публікації -->
                        <div class="mb-3">
                            <label for="id_date_of_publication" class="form-label">Дата публікації</label>
                            <input type="date"
                                   style="color: white"
                                   class="form-control"
                                   id="id_date_of_publication"
                                   name="date_of_publication"
                                   value="{{ form.instance.date_of_publication|date:'Y-m-d' }}">
                        </div>

                        <!-- Кнопки -->
                        <div class="d-flex justify-content-between mt-3">
                            <button type="submit" class="btn btn-success btn-lg px-4">Зберегти</button>
                            <a href="{% url 'article-list' %}" class="btn btn-secondary btn-lg px-4">Скасувати</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

townsNews/newportal/templates/catalog/article_statistics.html
{% extends 'base_generic.html' %}

{% block content %}
<div class="container mt-5 rat-container" style="background-color: #022926">
  <h1 class="text-center mb-5 stat-header" style="color: #ffcc00">
    Статистика статей
  </h1>

  <div class="row justify-content-center rat-table">
    <div class="col-lg-10">
      <table class="table table-bordered table-stat">
        <thead class="thead-dark">
          <tr>
            <th>Назва статті</th>

            <th>
              <a href="?sort=views" style="color: white; text-decoration: none">
                Перегляди
                {% if current_sort == 'views' %}{% endif %}
              </a>
            </th>

            <th>
              <a href="?sort=comments" style="color: white; text-decoration: none">
                Коментарі
                {% if current_sort == 'comments' %}{% endif %}
              </a>
            </th>

            <th>
              <a href="?sort=saves" style="color: white; text-decoration: none">
                Збереження
                {% if current_sort == 'saves' %}{% endif %}
              </a>
            </th>
          </tr>
        </thead>
        <tbody>
          {% for article in articles %}
          <tr>
            <td class="td-title">{{ article.title }}</td>
            <td class="count-rating">{{ article.views_count }}</td>
            <td class="count-rating">{{ article.num_comments }}</td>
            <td class="count-rating">{{ article.num_saves }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="4" class="text-center">Немає статей для відображення.</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

townsNews/newportal/templates/catalog/confirm_delete_article.html
{% extends 'base_generic.html' %}
{% block title %}Видалити статтю{% endblock %}

{% block content %}
<div class="container">
    <h1>Ви впевнені, що хочете видалити статтю "{{ article.title }}"?</h1>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Видалити</button>
        <a href="{% url 'article-detail' article.pk %}" class="btn btn-secondary">Скасувати</a>
    </form>
</div>
{% endblock %}

townsNews/newportal/templates/catalog/edit_settings.html
{% extends 'base_generic.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.19.4.css">

<script src="https://code.jquery.com/qunit/qunit-2.19.4.js"></script>

{% block content %}
<div class="container-edit mt-5 setting-form">
    <div class="settings-container card shadow p-4">
        <h2 class="text-center mb-4">Налаштування сайту</h2>
        <form method="post" class="settings-form text-left">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_font_color">Колір шрифту:</label>
                {{ form.font_color }}
            </div>
            <div class="form-group">
                <label for="id_background_color">Колір фону:</label>
                {{ form.background_color }}
            </div>
            <div class="form-group">
                <label for="id_font_size">Розмір шрифту:</label>
                <input type="range" id="id_font_size" name="font_size" min="12" max="36" step="1" value="{{ form.font_size.value }}">
                <span id="font-size-display">{{ form.font_size.value }} px</span>
            </div>
            <div class="text-center mt-4">
                <button type="submit" class="btn">Зберегти</button>
                <button type="submit" name="reset_defaults" value="1" class="btn">Скинути до стандартних</button>
            </div>
        </form>
    </div>
</div>
    <script src="{% static 'js/edit_settings.js' %}"></script>
{% endblock %}